[project]
name = "ai-agent-tutorials"
version = "0.1.0"
description = ""
authors = [
    {name = "kamleshcode",email = "kamleshit21@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "langchain (>=1.2.10,<2.0.0)",
    "langchain-openai (>=1.1.10,<2.0.0)",
    "chromadb (>=1.5.2,<2.0.0)",
    "langchain-community (>=0.4.1,<0.5.0)",
    "openai (>=2.26.0,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "langchain-groq (>=1.1.2,<2.0.0)",
    "pypdf (>=6.9.2,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
